### ISSUE TITLE
"un fichier .editorconfig pour favoriser les conventions du projet" ?

### ISSUE THREAD

**Issue by PhilippeVay** [alsacreations/schnapsit#1]
Je ne vois pas de fichier `.editorconfig` dans le Zip téléchargé ni dans le repo. Ce n'est pas `.gitignore` qui a empêché de le commiter, @raphaelgoetter @JulesAlexiu je vous laisse 🔍 ce qui peut manquer.

**Comment by raphaelgoetter** [comment]
bien vu, on s'en occupe
