### ISSUE TITLE
Débordement de contenu sur Safari mobile

### ISSUE THREAD

**Issue by the2ne** [alsacreations/schnapsit#4]
Sur Safari Mobile (et oui, toujours lui) avec un iPhone SE (1136x640px à 326 dpi) en 10.2 la grille contenant les trois éléments de formulaire sort du layout et provoque un scroll horizontal.

![Débordement](https://pbs.twimg.com/media/C16xo2EWQAQywJb.jpg)

Le zoom initial est bon, j'ai dézoomé pour les besoins du screenshot.

**Comment by raphaelgoetter** [comment]
Je n'ai pas ce bug sur notre iPhone 5 de test mais j'ai touché à certains trucs.
"Normalement" c'est résolu, tu peux confirmer ?

**Comment by the2ne** [comment]
Oui, j'ai toujours le même comportement. Je sors le Mac du placard et lance le débogueur ?

**Comment by raphaelgoetter** [comment]
"normalement" c'est mieux maintenant :)

**Comment by the2ne** [comment]
Impeccable ! Y a juste le "s" de "Analytics" qui se retrouve orphelin mais le problème initial est corrigé ;)
